# Referrence: https://synuns.tistory.com/75
name: CICD


on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4


      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.REACT_APP_AUTH_CLIENT_ID }}" > .env
      - name: Sign in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t rwewine/front_test_todo .
      - name: Push Docker Image
        run: docker push rwewine/front_test_todo:latest


  deploy:
    needs: build
    runs-on: aws-ec2
 —------ 이 부분까지 입력하고, 19 ~ 28번 절차 진행
    steps:
      - name: Pull image from docker hub
        run: docker pull rwewine/front_test_todo
      - name: Delete existing container
        run: docker rm -f reactContainer
      - name: Run container
        run: docker run -d -p 80:80 --name reactContainer rwewine/front_test_todo
